trying to implement classifier errors on runserver: problems with migrations I deleted the migrations I deleted the database and created a new one wanted to makemigrations, but get this error
raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
ERRORS:
?: (corsheaders.E013) Origin 'localhost:3000/' in CORS_ORIGIN_WHITELIST is missing scheme or netloc
	HINT: Add a scheme (e.g. https://) or netloc (e.g. example.com).

Something to do with the CORS_ORIGIN_WHITELIST in backend.settings.py?